/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:69ee61aa4207dfabb12b1ccf64278aee:14bb5e980c1ee3f4d94cc94e47e86a47:c9d2d723ee084d714db16650889dd273$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class EarthBossSprites
	{
		public const string Front1 = "Front1";
		public const string Front2 = "Front2";
		public const string Front3 = "Front3";
		public const string Front4 = "Front4";
		public const string Left1 = "Left1";
		public const string Left2 = "Left2";
		public const string Left3 = "Left3";
		public const string Left4 = "Left4";
		public const string Left5 = "Left5";
		public const string Left6 = "Left6";
		public const string Left7 = "Left7";
		public const string Left8 = "Left8";
		public const string Left9 = "Left9";
		public const string Right1 = "Right1";
		public const string Right2 = "Right2";
		public const string Right3 = "Right3";
		public const string Right4 = "Right4";
		public const string Right5 = "Right5";
		public const string Right6 = "Right6";
		public const string Right7 = "Right7";
		public const string Right8 = "Right8";
	}
}