/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:a4328255858e9aee821bfb239334ba89:6bcbe74f2ee9f4c78f335ad35b86d1fe:d3832a33021060234dcb0fe72aab45ce$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class FireBossSprites
	{
		public const string Layer_1 = "Layer_1";
		public const string Layer_2 = "Layer_2";
		public const string Layer_3 = "Layer_3";
		public const string Layer_4 = "Layer_4";
		public const string Layer_5 = "Layer_5";
		public const string Layer_6 = "Layer_6";
		public const string Layer_7 = "Layer_7";
		public const string Layer_8 = "Layer_8";
	}
}