/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:9b8eebcfb164f5c15530205508a63ccd:4036129f2214c14c2aa8248886a50468:e2b4fb17a14229f4ca1efacd45a113a7$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class GhostSprites
	{
		public const string Down1 = "down1";
		public const string Down2 = "down2";
		public const string Down3 = "down3";
		public const string Left1 = "left1";
		public const string Left2 = "left2";
		public const string Left3 = "left3";
		public const string Right1 = "right1";
		public const string Right2 = "right2";
		public const string Right3 = "right3";
		public const string Up1 = "up1";
		public const string Up2 = "up2";
		public const string Up3 = "up3";
	}
}