/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:910d88aee20ddad8e16d6d692f491676:c506ea8efc5fbac0e9ec4fb226e7b289:3ee1e86eed3541704143cecef77bb5b0$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class IceBossSprites
	{
		public const string Layer_1 = "Layer_1";
		public const string Layer_2 = "Layer_2";
		public const string Layer_3 = "Layer_3";
		public const string Layer_4 = "Layer_4";
		public const string Layer_5 = "Layer_5";
		public const string Layer_6 = "Layer_6";
	}
}