/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:8af0b458a6285203c515766dd632f35e:808bb13a326a56eb53f456e6c6315f25:68b3ca5487d298f3ebcae21c9c766c6a$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class IceMinionSprites
	{
        public const string Down1 = "Down1";
		public const string Up1 = "Up1";
		public const string Up2 = "Up2";
		public const string Up3 = "Up3";
		public const string Down2 = "Down2";
		public const string Down3 = "Down3";
		public const string Left1 = "Left1";
		public const string Left2 = "Left2";
		public const string Left3 = "Left3";
		public const string Right1 = "Right1";
		public const string Right2 = "Right2";
		public const string Right3 = "Right3";
	}
}