/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:950676d2b956e5eeca9123cfc9f51861:a1b4b25ece6b69efee142e048dd07576:35d0cea304e4bb9af3c6f2d0e62903f3$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class PortalSprites
	{
		public const string First = "First";
		public const string Second = "Second";
		public const string Third = "Third";
        public const string Fourth = "Fourth";
	}
}