/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:40d2a7c0f66e1b81320f64f116799e39:398afdf243ab5c106bb7d886674e121b:6306928a4f757e62f0414b65b26f75fd$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class SoldierSprite
	{
		public const string Backward_Layer_1 = "Backward/Layer_1";
		public const string Backward_Layer_2 = "Backward/Layer_2";
		public const string Backward_Layer_3 = "Backward/Layer_3";
		public const string Backward_Layer_4 = "Backward/Layer_4";
		public const string Backward_Layer_5 = "Backward/Layer_5";
		public const string Backward_Layer_6 = "Backward/Layer_6";
		public const string Backward_Layer_7 = "Backward/Layer_7";
		public const string Backward_Layer_8 = "Backward/Layer_8";
		public const string Backward_Layer_9 = "Backward/Layer_9";
		public const string Forward_Layer_19 = "Forward/Layer_19";
		public const string Forward_Layer_20 = "Forward/Layer_20";
		public const string Forward_Layer_21 = "Forward/Layer_21";
		public const string Forward_Layer_22 = "Forward/Layer_22";
		public const string Forward_Layer_23 = "Forward/Layer_23";
		public const string Forward_Layer_24 = "Forward/Layer_24";
		public const string Forward_Layer_25 = "Forward/Layer_25";
		public const string Forward_Layer_26 = "Forward/Layer_26";
		public const string Forward_Layer_27 = "Forward/Layer_27";
		public const string Left_Layer_10 = "Left/Layer_10";
		public const string Left_Layer_11 = "Left/Layer_11";
		public const string Left_Layer_12 = "Left/Layer_12";
		public const string Left_Layer_13 = "Left/Layer_13";
		public const string Left_Layer_14 = "Left/Layer_14";
		public const string Left_Layer_15 = "Left/Layer_15";
		public const string Left_Layer_16 = "Left/Layer_16";
		public const string Left_Layer_17 = "Left/Layer_17";
		public const string Left_Layer_18 = "Left/Layer_18";
		public const string Right_Layer_28 = "Right/Layer_28";
		public const string Right_Layer_29 = "Right/Layer_29";
		public const string Right_Layer_30 = "Right/Layer_30";
		public const string Right_Layer_31 = "Right/Layer_31";
		public const string Right_Layer_32 = "Right/Layer_32";
		public const string Right_Layer_33 = "Right/Layer_33";
		public const string Right_Layer_34 = "Right/Layer_34";
		public const string Right_Layer_35 = "Right/Layer_35";
		public const string Right_Layer_36 = "Right/Layer_36";
	}
}