/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:e2f2bbee82825f1a2bfbda8575d2f584:2fcf5ce8fc0e6352e587cab02a8cdac7:702d1ce76f30e236bcfcb5f8e7519831$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class SpeedBossSprites
	{
		public const string Layer_1 = "Layer_1";
		public const string Layer_2 = "Layer_2";
		public const string Layer_3 = "Layer_3";
		public const string Layer_4 = "Layer_4";
		public const string Layer_5 = "Layer_5";
		public const string Layer_6 = "Layer_6";
		public const string Layer_7 = "Layer_7";
		public const string Layer_8 = "Layer_8";
	}
}